### ISSUE TITLE
Webpack errors

### ISSUE THREAD

**Issue by anthony-pinskey** [angular/angular2-seed#71]
When running npm start, I get the following errors in the console:

    ERROR in [default] /Users/user-name/Desktop/angular2-seed-master/node_modules/@angular/common/src/facade/async.d.ts:27:32
    Cannot find name 'Promise'.

    ERROR in [default] /Users/user-name/Desktop/angular2-seed-master/node_modules/@angular/common/src/facade/async.d.ts:28:44
    Cannot find name 'Promise'.

    ERROR in [default] /Users/user-name/Desktop/angular2-seed-master/node_modules/@angular/common/src/facade/lang.d.ts:4:16
    Cannot find name 'Map'.

    ERROR in [default] /Users/user-name/Desktop/angular2-seed-master/node_modules/@angular/common/src/facade/lang.d.ts:5:16
    Cannot find name 'Set'.

I made sure to do all the steps in your readme. Any ideas what's up?

The app however serves and appears to run correctly when I navigate to http://localhost:3000, however the browser console is also full of errors as above.

thanks!

**Comment by wollio** [comment]
I fixed that problem with the following steps:

`npm install -D typings`

Then extend your package.json scripts with
`"postinstall": "typings install"`

finally run `npm install` again.

Not sure if this is the correct solution.

**Comment by bbottema** [comment]
I'm having the same issue at work and at home. At home I cleanly installed node and npm as well and followed the instructions to get up and running.

I simply forked this repo and didn't change anything.

node: 4.4.4
npm: 3.9.0
typings: 1.0.4

> ERROR in [default] C:/workstation/simple-java-mail/src/main/webapp/angular-app/node_modules/@angular/common/src/directives/ng_class.d.ts:72:34 
> Cannot find name 'Set'.
> 
> ERROR in [default] C:/workstation/simple-java-mail/src/main/webapp/angular-app/node_modules/@angular/common/src/facade/async.d.ts:27:32 
> Cannot find name 'Promise'.
> 
> ... snip a few hundres lines...
> 
> ERROR in [default] C:/workstation/simple-java-mail/src/main/webapp/angular-app/src/polyfills.ts:11:0 
> Cannot find name 'require'.

@wollio, your suggestion didn't work for me.

**Comment by bbottema** [comment]
Alright, I think I found the issue or at least I made the errors go away.

npm _typings_ went up a major release and made [some breaking changes](https://github.com/typings/typings/releases/tag/v1.0.0). One of which is that they renamed _ambient_ to _global_, as in "**ambient**Dependencies" to "**global**Dependencies".

As a result, I now have the following typings.json:

```
{
  "name": "angular2-seed",
  "version": false,
  "dependencies": {},
  "globalDependencies": {
    "es6-collections": "registry:dt/es6-collections#0.5.1+20160316155526",
    "es6-promise": "registry:dt/es6-promise#0.0.0+20160423074304",
    "node": "registry:dt/node#4.0.0+20160423143914"
  }
}

```

that or I changed it into an invalid name that is simply ignored now. Either way, the errors went away and the app still works as expected.

**Comment by anthony-pinskey** [comment]
@bbottema Perfect! Yes your solution was the only one that has worked for me so far. Thanks!

**Comment by vittau** [comment]
Did not work for me, I changed to `globalDependencies`, ran `npm run typings-install` again (though I'm not sure it's actually needed - still learning), and I still get a lot of these
```
ERROR in [default] PATH
Cannot find name 'NAME'.
```

Still, the application seems to be working as expected, even though the browser console has similar erros as well, thrown from `polyfills.bundle.js`.

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question that got resolved. Closing for now.
